services:
  api:
    build:
      context: .
    ports:
      - "8083:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq-dev
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    networks:
      - ms-rabbitmq
    depends_on:
      - db

  db:
    image: postgres:16
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ms_auth
    networks:
      - ms-rabbitmq
    ports:
      - "5434:5432"

networks:
  ms-rabbitmq:
    external: true